from image_processing.feature_extractor.shape_descriptor import ShapeDescriptor
from image_processing.feature_extractor.intensity import IntensityFeatures
from image_processing.feature_extractor.intensity_superpixel import IntensityFeatureSuperpixel